name: LaTeX CI

on:
  push:
    branches:
      - main  # adjust branch name as needed
  pull_request:
    branches:
      - main  # adjust branch name as needed

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

    - name: Install LaTeX
      run: sudo apt-get install texlive-full -y

    - name: Install Pygments for minted
      run: sudo apt-get install python3-pygments -y

    - name: Compile Documentation LaTeX file
      run: |
        pdflatex -interaction=nonstopmode -shell-escape adigraph_documentation.tex
        pdflatex -interaction=nonstopmode -shell-escape adigraph_documentation.tex
    
    - name: Compile Test LaTeX file
      run: |
          pdflatex -interaction=nonstopmode -shell-escape adigraph_working_test.tex
          pdflatex -interaction=nonstopmode -shell-escape adigraph_working_test.tex